# Dockerfiles are the same as in previous exercise, removed unnecesary port mappings

services:
  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    depends_on:
      - backend

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    depends_on:
      - backend

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

volumes:
  database:
